=== AngeldelaNava/HospitalDatabase/XML/Hospital.dtd
<!ELEMENT Hospital (name, city, ListOfWorkers)>
   <!ELEMENT name (#PCDATA)>
   <!ELEMENT city (#PCDATA)>
   <!ELEMENT ListOfWorkers (Worker+)>
   <!ELEMENT Worker (name, job, salary, hireDate, endDate)>
   <!ELEMENT name (#PCDATA)>
	<!ELEMENT job (#PCDATA)>
	<!ELEMENT salary (#PCDATA)>
	<!ELEMENT hireDate (#PCDATA)>
	<!ELEMENT endDate (#PCDATA)>	
<!ATTLIST Worker id CDATA #REQUIRED>

=== AngeldelaNava/HospitalDatabase/XML/Hospital.xml
<?xml version="1.0"?>


<!DOCTYPE Hospital SYSTEM "Hospital.dtd">
<Hospital>
<name>Hospital Clínico</name>
<city>Madrid</city>
<ListOfWorkers>

<Worker id="03">
<name>Marta Bañon</name>
<job>Biomedical Engineer</job>
<salary>6000</salary>
<hireDate>14/10/2014</hireDate>
<endDate>02/01/2027</endDate>
</Worker>

<Worker id="04">
<name>Sofia Chollet</name>
<job>Surgeon</job>
<salary>9000</salary>
<hireDate>21/09/2010</hireDate>
<endDate>01/05/2050</endDate>
</Worker>

<Worker id="05">
<name>Angel de la Nava</name>
<job>Nurse</job>
<salary>1000</salary>
<hireDate>17/09/2020</hireDate>
<endDate>23/05/2025</endDate>
</Worker>
</ListOfWorkers>
</Hospital>
